/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EasyOrganizer.UI;

import EasyOrganizer.db.DBHandler;
import EasyOrganizer.model.EasyOrganizerModel;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author superman
 */
public class List extends javax.swing.JPanel {

    /**
     * Creates new form List
     */
    private DBHandler dbh;
    private JPanel contentPanel;
    
    public List(JPanel contentPanel) {
        this.contentPanel = contentPanel;
        dbh = new DBHandler();
        initComponents();
        addRowTable();
    }
    
    public void addRowTable(){
        DefaultTableModel dtm = (DefaultTableModel) listTable.getModel();
        ArrayList<EasyOrganizerModel> eoms = (ArrayList<EasyOrganizerModel>) dbh.selectAll();
        System.out.println(eoms);
        Object rowData[] = new Object[4];
        for(EasyOrganizerModel eom : eoms){
            rowData[0] = eom.getTitle();
            rowData[1] = eom.getSubject();
            rowData[2] = eom.getDescription();
            rowData[3] = eom.getDate();
            dtm.addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(450, 450));

        listTable.setFont(new java.awt.Font("Lucida Sans", 0, 15)); // NOI18N
        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Assunto", "Descrição", "Data"
            }
        ));
        jScrollPane1.setViewportView(listTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listTable;
    // End of variables declaration//GEN-END:variables
}
